### ISSUE TITLE
How to create jwk_1_d and jwk_1_n

### ISSUE THREAD

**Issue by wzhonggo** [winstonhong/Apache-Oltu-OpenID-Connect-Client-and-Provider#5]
Hi,

I want to update  **jwk_1_d** and **jwk_1_n** in  **org.apache.oltu.oauth2.provider.demo.OIDC**,  but i am not success. So please tell me how to create.

**Comment by winstonhong** [comment]
The following link provides the instruction on how to use Command line JSON Web Key (JWK) generator to create jwk_1_d and jwk_1_n.

java -jar json-web-key-generator.jar -t RSA -s 2048 -i 1 -u sig -S

https://connect2id.com/products/nimbus-jose-jwt/generator

**Comment by wzhonggo** [comment]
It is work, thank you very much.
